apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXpYbkhSWWFVZmluNTBUR1o4ZzBvczNVVzNod0toWG8wc1AzVUhnR2tHRXRjCmxvTWRVdUZCTm45NzdkdjBhcWt5UHFQSGF4MVF2N0daclJlOW53VE9tSHZEcG1NcjUycGU5Rk8wTjI1Z2l0V3UKc2JuQyt5azZTYnI1MFJGeTdjandUMnpTR3BwT3BDY1ZPSGNHY1JWVCtiNXJydDhFMmVKZ004aGw4cHZQUmhzRQpUYTJyUGtzNXJEUmlqL3VzU00xZzBEMTllUmhqdy9hSm9PdXRRdUV5SDJaWHd5VEdPOUlQTGxrcTdwaElZdk1FCkNpMzhrQ0pDQnl3RFhUNmh2enlkMWl6L01pMnNIaUNES0FpdTlhL251NWY2V0wwUVhhNmNaRHJ3ekNhazQrSzQKR1Bma0ExNWJwR2VOWnByd29QRFVwTjhESzRXUTd3Y0RlWWZ6TjROK25RSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBTGJHc3VpbFVWZ2hDNXpsc1QrNnRxTXg1TEZEaVJBekJPdldXMXBqMXp3bUtjemg5Rk5uClU1OTQxTGhjRy9XV05VWkIvM1ZSVEZmL3dEdUsrdHNLTmN3TXA5eW4vY2RSekZETk5IcEQ5VDc0QUw0aTA3UDUKdkZIQ3lyS1IyZWxaR0tza3ArUEt1ck9lUmVwOVM1NXVLSjFKL1hFZTJ5U2gzSDE4M2JuOStZOGQwUGRRcjZlTApKODFwWjl4Y1BLdU9lbXI4TTlRdnU5WDlhNzFkT28rdUQvWHdUTjhqME9LTlN4RVlOd25lai9wWExTMmRQekY1CnJ3K3VMMHhJRUh3ZzBtSzBIa1B5ekYyVEdDSXBYeThsU3VGWXNXTEdrSXZxYmhNR28zZHZDN3FmbUxVMVJ2ZDYKbWJodnJPbTI5a3pya3BoSFprelViWkc4MElpYXhNTUNxNnc9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - server auth
